services:
  # The Bones
  db:
    image: ankane/pgvector:v0.5.1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
      POSTGRES_DB: aperture_note
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./apps/server:/app        
      - /app/node_modules

  # The Brain
  agent:
    build: ./apps/agent
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # The Nervous System
  server:
    build: ./apps/server
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=${DATABASE_URL} 
      - AGENT_URL=${AI_AGENT_URL}
      - JWT_SECRET=${JWT_SECRET}
      - REFRESH_SECRET=${REFRESH_SECRET}
    depends_on:
      - db
      - agent

volumes:
  pgdata: